### ISSUE TITLE
Linking to external codelists

### ISSUE THREAD

**Issue by caprenter** [IATI/IATI-Codelists#4]
Where forexample in a codelists that is for vocabularies, we should provide a link to more information about each option - this could be a URL in the description, or the codelist schema could include the external source as an element, or...

discuss!

**Comment by caprenter** [comment]
This has come up in the 1.04 proposed changes.
Here for example:
https://docs.google.com/spreadsheet/ccc?key=0AnWngmdQt3stdFNxVS1NdmpzSnR3aTBmUG1OWS1uZXc&usp=drive_web#gid=15

URLs are provided and I think are supposed to be on the codelist.

**Comment by Bjwebb** [comment]
From the other issue:
"How should our codelists deal with these URLs. In this case the URL endpoints are not machine readable as such. Would that make a difference if they were?"

**Comment by Bjwebb** [comment]
Since we also need to add urls when we add the [registration agency list](https://docs.google.com/spreadsheet/ccc?key=0AnWngmdQt3stdFppMWdkcXJqVTRWTk9menR1N0FXNGc&usp=drive_web#gid=0) I think the best approach to this is to add an extra `url` element containing within a `<codelist-item>`.

The advantage of `url` as an element name over `website` as it it is more inclusive of the fact that linked contents might not be HTML.

**Comment by caprenter** [comment]
Good!
