### ISSUE TITLE
Implement 2.01 "Addition to RelatedActivityType Codelist"

### ISSUE THREAD

**Issue by Bjwebb** [IATI/IATI-Codelists#42]
http://support.iatistandard.org/entries/76862583-Referencing-another-publisher-s-report-of-the-same-activity

**Comment by Bjwebb** [comment]
@bill-anderson Need a name for the new code before I can usefully add it.

**Comment by bill-anderson** [comment]
@bill-anderson to add to discussion. Rename multifunded to cofunded, (and change definition). And add new code Other

**Comment by caprenter** [comment]
This is also a 1.05 issue - see the post at:
http://support.iatistandard.org/entries/54201556-related-activity-new-code

**Comment by bill-anderson** [comment]
Herman's discussion on http://support.iatistandard.org/entries/76862583-Referencing-another-publisher-s-report-of-the-same-activity is wrong. So this is not needed in 2.01 as all sorfed in 1,5

Comment added

**Comment by caprenter** [comment]
All 1.05 codelist changes are being applied in 2.01.

@bill-anderson This issue still needs the following clarifications:
- [x] You say above that you need to "Rename multifunded to cofunded, (and change definition)" this still needs doing
- [x] You refer to the code as both 'Other' and 'Third Party' in various places - which is it please?

[You use 'Other' above. 'Third party' in the issue here: http://support.iatistandard.org/entries/54201556-related-activity-new-code
and 
"Other/Third Party" here: http://support.iatistandard.org/entries/76862583 ]

**Comment by bill-anderson** [comment]
Yes, rename multifunded to Co-funded. 
Description. An activity that receives funding from more than one organisation.

I think "Third Party" is better. 

5 - Third Party - A report by another organisation on the same activity (excluding activities reported as part of financial transactions - eg. provider-activity-id - or a co-funded activity using code = 4)
